In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('../data/olist.db')
print("Connected ✓")

Connected ✓

In [3]:
query = """
SELECT
    MIN(order_purchase_timestamp) as earliest,
    MAX(order_purchase_timestamp) as latest,
    COUNT(DISTINCT customer_id)   as total_customers,
    COUNT(DISTINCT order_id)      as total_orders
FROM orders
WHERE order_status = 'delivered'
"""
pd.read_sql_query(query, conn)

              earliest               latest  total_customers  total_orders
0  2016-09-15 12:16:38  2018-08-29 15:00:37            96478         96478

In [4]:
query = """
SELECT
    purchase_count,
    COUNT(*)  as num_customers,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER(), 1) as pct
FROM (
    SELECT c.customer_unique_id,
        COUNT(DISTINCT o.order_id) as purchase_count
    FROM customers c
    JOIN orders o ON c.customer_id = o.customer_id
    WHERE o.order_status = 'delivered'
    GROUP BY c.customer_unique_id
)
GROUP BY purchase_count
ORDER BY purchase_count
LIMIT 10
"""
pd.read_sql_query(query, conn)

   purchase_count  num_customers   pct
0               1          90557  97.0
1               2           2573   2.8
2               3            181   0.2
3               4             28   0.0
4               5              9   0.0
5               6              5   0.0
6               7              3   0.0
7               9              1   0.0
8              15              1   0.0